easymod mgn12
EVA-3D/contrib-extras pull request #4
Opened 2021-03-03 00:22 UTC by EduardoOliveira

## Part name
Easymod mgn12
## Compatible EVA version
 2.1.0 - 2.2.0
## Related EVA parts
Easymod XY joinners
## Necessary Hardware BOM
3mm longer 5mm screws if you intend to use mgn12 on Y as well
## Description
It enables the usage of mgn12 in the X axis and mgn12c or mgn12h in Y
## Onshape or STEP files
https://cad.onshape.com/documents/8559b0e7f5d3b30427c227c5/w/d70f098c5b327e06a1ae23f4/e/12a2436a47701eb37945bb45?configuration=List_ByYG67Ay22XcMs%3DMGN12 

https://cad.onshape.com/documents/8559b0e7f5d3b30427c227c5/w/d70f098c5b327e06a1ae23f4/e/67166bbf807ca01f4a1ac8b3?configuration=List_V5TmcWwH5u18OA%3DDefault
## Print instructions
To print the adapter plates increase tops and bottoms and infill at ~50%
## Contributor
Me EOliveira @ discord

2021-03-03 14:46 UTC, miklschmidt requested changes
Thank you for your contribution! I have a few change requests before merging, mainly spelling errors and a couple of headers. Other than that, very nice!

2021-03-03 14:46 UTC, miklschmidt commented on docs/easymod/em_mgn12.md
> +The XY joiners are drop in replacement for the official ones.
Change `are drop in` to `are a drop in`.

2021-03-03 14:46 UTC, miklschmidt commented on docs/easymod/em_mgn12.md
> +This will allow you to use your setup with mgn12 in the X axis, mainly redugin the weight of it.
Change `redugin` to `reducing`

2021-03-03 14:46 UTC, miklschmidt commented on docs/easymod/em_mgn12.md
> +An implementation of easymod 1.2.1 using mgn12
Change to `# An implementation of MGN12 for EasyMod 1.2.1`

2021-03-03 14:46 UTC, miklschmidt commented on docs/easymod/em_mgn12.md
> +
add 
```
# Compatible EVA versions
1.2.1
# BOM
```

2021-03-03 14:46 UTC, miklschmidt commented on docs/easymod/em_mgn12.md
> +If you are also using mgn12C or MGN12H on the Y axis you'll need the following adapters in place of the original aluminum plates.
change `mgn12C` to `MGN12C`

2021-03-03 14:46 UTC, miklschmidt commented on docs/easymod/em_mgn12.md
> +You'll need longer M5 screws as this adapters are 3mm thicker than the aluminum part. I recomend printing with more tops/bottoms and higher infill to incease strength.
change `as this adapters` to `as these adapters` and `I recomend` to `I recommend`.

2021-03-03 15:00 UTC, EduardoOliveira commented
Thank you for the changes

2021-03-04 21:47 UTC, miklschmidt approved these changes

2021-03-04 21:47 UTC, merged